# Generated by Django 4.1 on 2022-08-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
