# Generated by Django 4.1 on 2022-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_team_division_alter_team_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
