# Generated by Django 4.1 on 2022-08-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='League_NFL',
            new_name='NFL_Teams',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postion', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('injured', models.CharField(max_length=100)),
                ('nfl_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='rest.nfl_teams')),
            ],
        ),
    ]
